git:
  depth: 5

branches:
  only:
    - master

os:
  - osx

sudo: false

language: ruby

cache:
  directories:
    - build/cache
    - node_modules
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Cellar 

rvm:
  - 2.2.3

before_install:
  # Homebrew
  - brew update
  - brew install Caskroom/cask/xquartz wine mono gnu-tar libicns graphicsmagick xz
  - tar czf ./homebrew-cache.tar.gz --directory /usr/local/Cellar gnu-tar libicns graphicsmagick xz libpng freetype jpeg libtool libusb libusb-compat fontconfig libtiff webp gd libgphoto2 little-cms2 libicns wine 
  - curl -T ./homebrew-cache.tar.gz -usidneys:$BINTRAY_TOKEN https://api.bintray.com/content/sidneys/electron-crossplatform-build-environment/homebrew/1.0.0/homebrew-cache.tar.gz
  # electron-installer-debian (github.com/unindented/electron-installer-debian#requirements)
  - brew install fakeroot dpkg; brew info fakeroot dpkg
  
install:
  - export PATH=~/bin:$PATH
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | NVM_DIR=$HOME/.nvm sh
  - source $HOME/.nvm/nvm.sh
  - command -v nvm
  - nvm install 6.3.0
  - nvm use 6.3.0

before_script:
  - npm prune
  - npm install

script:
  - npm run-script build

notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
